### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_tracks'

### ISSUE THREAD

**Issue by MinerChAI** [EvieePy/Wavelink#12]
```py
Traceback (most recent call last):
  File "/home/ivan/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ivan/GitHub/Black-Cat/ext/music.py", line 444, in play_
    tracks = await self.bot.wavelink.get_tracks(query)
  File "/home/ivan/.local/lib/python3.6/site-packages/wavelink/client.py", line 100, in get_tracks
    return await node.get_tracks(query)
AttributeError: 'NoneType' object has no attribute 'get_tracks'
```
i use advanced example with some changes (removed Bot class and its instanting to make it extension)

[music.py](https://paste.pythondiscord.com/ujudusacap.py)
[application.yml](https://paste.pythondiscord.com/odecuzefun.yml)

**Comment by PendragonLore** [comment]
This usually means that the bot did not successfully connect to your lavalink server or that the node disconnected.

**Comment by MinerChAI** [comment]
Btw I can't join the support guild

**Comment by scragly** [comment]
@MinerChAI Sorry, the invite recently changed: https://discord.gg/RAKc3HF

**Comment by MinerChAI** [comment]
Lol I forgot to run lavalink server
