### ISSUE TITLE
Your support server link is invalid

### ISSUE THREAD

**Issue by Skullbite** [EvieePy/Wavelink#25]
maybe it's me but i can't join 
![Screenshot_20190918-082826](https://user-images.githubusercontent.com/20869262/65149274-cbbbbb80-d9ef-11e9-83ca-eb72cd496d75.png)

**Comment by SnowyLuma** [comment]
The invite link is valid, can you tell us your account Tag to see if you may be banned?

**Comment by Skullbite** [comment]
sorry i'm an idiot.
